#!/usr/bin/env bash
set -e

case "$1" in
  up)
    docker compose up --build -d
    ;;
  down)
    docker compose down
    ;;
  test)
    docker compose run --rm tests pytest --maxfail=1 --disable-warnings -q
    ;;
  lint)
    docker compose run --rm lint
    ;;
  shell)
    docker compose run --rm web bash
    ;;
  *)
    echo "Usage: dc {up|down|test|lint|shell}"
    exit 1
    ;;
esac
