# Generated by Django 5.1.11 on 2025-07-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="planetevent",
            index=models.Index(
                fields=["consumed_at"], name="analytics_p_consume_8235ac_idx"
            ),
        ),
    ]
