# Generated by Django 5.1.11 on 2025-07-10 20:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_planetevent_analytics_p_consume_8235ac_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planetevent",
            name="consumed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
