# Generated by Django 5.1.11 on 2025-07-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planet",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="planet",
            name="population",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
