# Generated by Django 5.1.11 on 2025-07-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planets", "0002_alter_planet_name_alter_planet_population"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planet",
            name="climates",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of climate types for the planet.",
            ),
        ),
        migrations.AlterField(
            model_name="planet",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when the planet entry was created.",
            ),
        ),
        migrations.AlterField(
            model_name="planet",
            name="name",
            field=models.CharField(
                help_text="Name of the planet (must be unique).",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="planet",
            name="population",
            field=models.IntegerField(
                blank=True, help_text="Population of the planet (nullable).", null=True
            ),
        ),
        migrations.AlterField(
            model_name="planet",
            name="terrains",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of terrain types for the planet.",
            ),
        ),
        migrations.AlterField(
            model_name="planet",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp when the planet entry was last updated.",
            ),
        ),
    ]
